#include "framebuffer.h"
#include "serial.h"

char myname[] = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum congue dapibus tempor. Donec vel purus augue. Nullam ornare bibendum mauris quis interdum. Nam a nisi dignissim, efficitur ex quis, aliquam velit. Ut velit orci, tempus eu molestie ac, vehicula at dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin dignissim facilisis magna, eu tincidunt enim sodales sit amet. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris nec hendrerit mauris. Phasellus eros erat, venenatis in commodo quis, sagittis blandit ipsum. Nunc turpis nulla, faucibus vitae arcu in, aliquet faucibus ante. Quisque vitae sem sed metus ultricies finibus at sit amet sapien. Nam interdum eros a libero pulvinar, sit amet interdum erat consequat. Nam vitae interdum nisl. Curabitur vestibulum est in tincidunt pulvinar. Quisque aliquet eget dui in aliquet. Quisque eget metus varius dui ullamcorper consequat at a quam. Morbi ut facilisis nunc. Cras convallis, turpis id molestie iaculis, ex libero pellentesque diam, id vulputate risus risus euismod enim. Ut suscipit vulputate dolor, in tempus ligula auctor eu. Fusce non dui a nisl fermentum commodo. Aenean congue, leo in dignissim sollicitudin, ipsum nisi lobortis leo, et dignissim ante elit in ligula. Aliquam finibus eu turpis vitae luctus. Proin orci libero, feugiat a feugiat at, dictum quis odio. Nulla facilisi. Ut eget faucibus risus. In hac habitasse platea dictumst. Morbi malesuada hendrerit ex, vitae commodo tellus rhoncus eu. Aliquam sollicitudin mattis euismod. In venenatis diam quis arcu porttitor sollicitudin. Cras volutpat, lectus ut ullamcorper pulvinar, nisi mauris tristique lorem, at vestibulum neque urna ac elit. Proin volutpat consequat eleifend. Praesent semper ipsum eget velit semper, ac ultrices neque ullamcorper. Integer elementum ac nunc non semper. Proin lacus enim, fringilla vitae luctus sit amet, accumsan eu augue. Aliquam venenatis metus vitae sagittis vulputate. Etiam ullamcorper turpis quis eros vehicula commodo. Sed ut diam vel est feugiat facilisis. Ut accumsan mauris eu pretium pulvinar. Nullam iaculis, nisl sit amet molestie hendrerit, magna tortor fringilla lectus, eget tempor felis tellus ut augue. Phasellus malesuada enim nisi, at lacinia odio tincidunt eget. Maecenas faucibus hendrerit ligula. Etiam dui orci, lobortis vel sollicitudin id, suscipit eget purus. Sed sit amet convallis est. Morbi venenatis libero nec libero varius pellentesque. Nulla facilisi. Integer pellentesque fringilla leo vitae aliquam. Cras sed justo eget nisi cursus pretium. Sed et consectetur metus, in auctor justo.";

/** kmain:
 *  The main function the kernel calls before it goes into an infinite loop
 */
 void kmain() {
 	serial_write(DEBUG_SERIAL, myname, 2652);
 }
